config/routes.rb
Pubsub::Application.routes.draw do
  resources :notifications

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = Notification.all
  end

  def show
    @notification = Notification.find(params[:id])
  end

  def new
    @notification = Notification.new
  end

  def edit
    @notification = Notification.find(params[:id])
  end

  def create
    @notification = Notification.new(params[:notification])

    if @notification.save
      $redis.publish('notifications.create', @notification.to_json)
      redirect_to @notification, notice: 'Notification was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @notification = Notification.find(params[:id])

    if @notification.update_attributes(params[:notification])
      redirect_to @notification, notice: 'Notification was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    redirect_to notifications_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pubsub</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table id="notifications">
  <tr>
    <th>Message</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notifications.each do |notification| %>
  <tr>
    <td><%= notification.message %></td>
    <td><%= link_to 'Show', notification %></td>
    <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
    <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notification', new_notification_path %>

<script type="text/javascript" charset="utf-8">
$(function(){
  var socket = io.connect('//localhost:3001/');

  socket.on('message', function (data) {
    data = JSON.parse(data);
    console.log(data);

    var notification = $("<tr/>", {
      html: $("<td/>", { text: data.message })
    });
    $('#notifications').append(notification)

  });

});
</script>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message:</b>
  <%= @notification.message %>
</p>


<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>